### ISSUE TITLE
HELP - Videos not downloading

### ISSUE THREAD

**Issue by natcoso9955** [RandomNinjaAtk/docker-amvd#1]
For some reason no videos download.
Lidarr is scanned perfectly, and it appears that it connects to imvdb but it never downloads any videos.

```
######################################### DOWNLOADING VIDEOS #########################################
2 of 7 :: Linkin Park :: Processing
2 of 7 :: Linkin Park :: Normalizing MBZDB Release Info (Capitalization)
2 of 7 :: Linkin Park :: IMVDB :: Aritst Link Found, using it's database for videos...
2 of 7 :: Linkin Park :: IMVDB :: Aritst Link Found, using it's database for videos...
2 of 7 :: Linkin Park :: MBZDB :: 1740 recordings found...
2 of 7 :: Linkin Park :: MBZDB :: Checking 1740 recordings for videos...
2 of 7 :: Linkin Park :: MBZDB :: 179 video recordings found...
2 of 7 :: Linkin Park :: MBZDB :: Checking 179 video recordings for links...
2 of 7 :: Linkin Park :: MBZDB :: 24 video recordings with links found!
2 of 7 :: Linkin Park :: MBZDB :: Processing 24 video recordings...
2 of 7 :: Linkin Park :: MBZDB :: Checking 1740 recordings for videos...
2 of 7 :: Linkin Park :: MBZDB :: 179 video recordings found...
2 of 7 :: Linkin Park :: MBZDB :: Checking 179 video recordings for links...
2 of 7 :: Linkin Park :: MBZDB :: 24 video recordings with links found!
2 of 7 :: Linkin Park :: MBZDB :: Processing 24 video recordings...
2 of 7 :: Linkin Park :: 0 Videos Downloaded!
2 of 7 :: Linkin Park :: MARKING ARTIST AS COMPLETE
######################################### 0 VIDEOS DOWNLOADED #########################################
```
Config
```
######################################### CONFIGURATION VERIFICATION #########################################
Musicbrainz Mirror Valid: https://musicbrainz.org
Musicbrainz Rate Limit: 1 (Queries Per Second)
Music Video Library Location: /mnt/user/Media/MusicVideos
Music Video Country Code: us
Music Video Require Match: DISABLED
Music Video Format Set To: --format bestvideo[vcodec*=avc1]+bestaudio --cookies /cookies/youtube.com_cookies.txt
Music Video Filter: DISABLED
Music Video Subtitle Language: en
Music Video NFO Writer: DISABLED
Music Video File Permissions: 666
Music Video Extension: mkv
```
NOTE i removed the secondary filter to see if that was issue, (didnt understand its use, no difference with it)

What have i done wrong????

**Comment by RandomNinjaAtk** [comment]
So one thing I see, is your Format is set incorrectly. 

Your cookies file should be stored in 
/config/cookies/cookies.txt

Follow on, just curious enable this setting: `-e RequireVideoMatch=true` (Music Video Require Match)

Give that a try and report back.

**Comment by natcoso9955** [comment]
Yeah figured out how you're doing the caching, i like it.
So we have progress, it appears to be trying now..maybe.

```
2 of 7 :: Linkin Park :: IMVDb :: 14 of 42 :: MBZDB MATCH :: Lost In The Echo :: Checking for match
2 of 7 :: Linkin Park :: IMVDb :: 14 of 42 :: MBZDB MATCH :: Track 1 :: Lost in the Echo :: Living Things :: Official :: KR :: Album :: 2012
2 of 7 :: Linkin Park :: IMVDb :: 14 of 42 :: DOWNLOAD :: Lost in the Echo :: Processing (https://www.youtube.com/watch?v=co4YpHTqmfQ)... with youtube-dl
2 of 7 :: Linkin Park :: IMVDb :: 14 of 42 :: MBZDB MATCH :: Track 1 :: Lost in the Echo :: Living Things :: Official :: KR :: Album :: 2012
2 of 7 :: Linkin Park :: IMVDb :: 14 of 42 :: DOWNLOAD :: Lost in the Echo :: Processing (https://www.youtube.com/watch?v=co4YpHTqmfQ)... with youtube-dl
2 of 7 :: Linkin Park :: IMVDb :: 14 of 42 :: DOWNLOAD :: Lost in the Echo :: Downloaded Failed!
```
ill try adding --verbose and see what i get.

**Comment by RandomNinjaAtk** [comment]
I only ever use it with matching enabled, so it may just be broken with that being disabled. I don't always test every permutation.... 

Thinking about the cookies thing, it probably would work by how it is designed. So your setting probably actually isn't invalid.... It is important to have though because youtube tends to get angry without it...

**Comment by natcoso9955** [comment]
> Thinking about the cookies thing, it probably would work by how it is designed. So your setting probably actually isn't invalid.... It is important to have though because youtube tends to get angry without it...

Oh it took me so long to figure out how to make unraid youtube-dl get past the 429 error. Drove me crazy with everyone saying you needed to open in a browser and stuff. was like, it works on my laptop which is on the same network, ended up just grabbing cookie from laptop and using that, instantly worked.

So putting verbose, actually doesnt give any additional output, :(
Also added -4 to force ipv4, but still getting a fail.

**Comment by RandomNinjaAtk** [comment]
@natcoso9955 see my edit above

**Comment by RandomNinjaAtk** [comment]
An image update should be pushed shortly with minor changes to enable youtube-dl output by default...

https://github.com/RandomNinjaAtk/docker-amvd/commit/6a2eb8a30d6817bb2f797e861dbe836135c3ec1e

**Comment by natcoso9955** [comment]
Hmm, so it seems to not like my cookies file now.

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--cookies', '/config/cookies/cookies.txt', '-o', '/mnt/user/Media/MusicVideos/Breaking Benjamin - Never Again', '--format', 'bestvideo[vcodec*=avc1]+bestaudio', '--cookies', '/cookies/cookies.txt', '-4', '--verbose', '--write-sub', '--sub-lang', 'en', '--embed-subs', '--merge-output-format', 'mkv', '--no-mtime', '--geo-bypass', 'https://www.youtube.com/watch?v=zEUG3_Zh-rw']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.07.28
[debug] Python version 3.8.2 (CPython) - Linux-4.19.107-Unraid-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4
[debug] Proxy map: {}
[youtube] zEUG3_Zh-rw: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 429: Too Many Requests (caused by <HTTPError 429: 'Too Many Requests'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
.
.
.
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 474, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 467, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 566, in __exit__
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 2774, in save
FileNotFoundError: [Errno 2] No such file or directory: '/cookies/cookies.txt'
```

Let me check the other youtube-dl thing i have, and see what that does.

**Comment by RandomNinjaAtk** [comment]
@natcoso9955 

Looks like you moved the cookes file, but you did not remove it from your format command. Causing it to be duplicated. Which is why your getting an error stating '/cookies/cookies.txt' does not exist...

**Comment by natcoso9955** [comment]
no cookie is still in the spot, also weirdly it seems it does modify it. hahaha
changes it to say its been generated by youtube-dl, so i think thats a false positive.

I think im back to trying to make my cookies work with youtube-dl. :( *sigh*

**Comment by RandomNinjaAtk** [comment]
Image update should be available, maybe give it a try

**Comment by natcoso9955** [comment]
okay i think the issue was that i was pointing to the cookie wrong. it seems it needs to be in the cookies folder to work (which i had initially), but i was referencing it as just /cookies/cookies.txt

but i had to reference it as /config/cookies/cookies.txt
So user error, but also the fact that it is looking for cookies.txt in the cookies folder for it to actually attempt is odd. But good to know.

Didnt try new image yet, i will do and advise.

**Comment by RandomNinjaAtk** [comment]
If you have cookies.txt stored in this: /config/cookies

You do not need to add that to your format command, the script adds it automatically if it detects the file there...

**Comment by natcoso9955** [comment]
oh, i will also try with that then, thats also good to know.

**Comment by RandomNinjaAtk** [comment]
Correct

**Comment by natcoso9955** [comment]
Updating working well, and removed my --cookies flag and its working as intended.
Sorry about that. knowing that it HAS to be called cookies.txt and that it picks it up automatically was the key part.

Suggestion, include in the unraid CA description a NOTE: Cookies file must be named cookies.txt & can simply be placed in the cookies folder without referencing it.

I mean people can obviously come find this if they have issues, my fault, once i figured out for something else about the cookies flag i just assumed anything using youtube-dl would need that flag. hahaha
