### ISSUE TITLE
[enhancement] Filter Lidarr Artists by Tag

### ISSUE THREAD

**Issue by shapechecker21** [RandomNinjaAtk/docker-amvd#14]
With a large Lidarr library, I only want to download videos for some artists. It would be great if I could tag an artist and only grab videos for artists with the that tag.

**Comment by KINGLIFER** [comment]
Is this abandoned?

**Comment by RandomNinjaAtk** [comment]
All development is being moved to: https://github.com/RandomNinjaAtk/docker-lidarr-extended
