### ISSUE TITLE
container script

### ISSUE THREAD

**Issue by nathanB84** [RandomNinjaAtk/docker-amvd#16]
Hi ninja. 
Im new to all this and have been following all your instructions, I have the docker installed and used your example script inputting all the required information (container created sucsessfully) however when I run the start up script I am getting two errors. one of which its telling me to input country code even though I have added the line -e CountryCode=AU 
second is its telling me to specify source connection even though I have put in the line -e SOURCE_CONNECTION=lidarr \ as directed by you. and have put in the lidarr ip in the correct line too. can you help me resolve these two issues please

**Comment by RandomNinjaAtk** [comment]
You should hop on discord for assistance
