### ISSUE TITLE
Is this supposed to download all videos

### ISSUE THREAD

**Issue by CubeComming** [RandomNinjaAtk/docker-amvd#18]
So I set the script up to download music videos for my Musiklibrary. It startet reading all artists and then started downloading. 
But it also downloadedd video for files I don't have, which messes up my Plex config. 
Is it supposed to do that?

**Comment by RandomNinjaAtk** [comment]
all artists & all music videos for that artist

**Comment by CubeComming** [comment]
Thank you,

Is there a way to only download videos for music i own?

**Comment by RandomNinjaAtk** [comment]
no

**Comment by CubeComming** [comment]
Okay thank you

**Comment by CubeComming** [comment]
Okay thank you

**Comment by Ahsome** [comment]
Is this a specific design of the application, or just a missing feature? I wouldn't mind helping creating a PR to implement the feature, assuming its possible

**Comment by RandomNinjaAtk** [comment]
@Ahsome PR's welcome, feel free to join discord for discussion...
