### ISSUE TITLE
Artist folder

### ISSUE THREAD

**Issue by Protektor-Desura** [RandomNinjaAtk/docker-amvd#2]
Is there any chance that there is some configuration I could change to add artist folders to the download locations? So the videos could be sorted by artist folders?

**Comment by RandomNinjaAtk** [comment]
Depending on the app your integrating with, they might not support using the files that way. This was designed to try to enable maximum app compatibility. If you can test and see what apps it works with, I'd consider it.

**Comment by Protektor-Desura** [comment]
Mainly asking for Jellyfin to make it a little more organized. Right now Jellyfin music videos is kind of unstructured in that it doesn't really care how things are organized too much. In fact the IMVDb metadata plugin is currently not working at the moment with the latest Jellyfin because no one has bothered to update it.

**Comment by Protektor-Desura** [comment]
Mainly asking for Jellyfin to make it a little more organized. Right now Jellyfin music videos is kind of unstructured in that it doesn't really care how things are organized too much. In fact the IMVDb metadata plugin is currently not working at the moment with the latest Jellyfin because no one has bothered to update it. It looks like Jellyfin & Emby would prefer:
/music-videos/artist/song

**Comment by davralin** [comment]
I also would prefer something like `Artist.Name/Artist.Name.-.Title.ext`.

Realising it will break app-compatibility, it could perhaps be easier to add an environment-variable for `FLAT_FILE_STRUCTURES=TRUE` (with a default of false, obviously) which would just dump them to a folder structure instead.

It seems all the apps have different ways of handling this, so maybe what's really needed is to specify the app you want supported...

**Comment by RandomNinjaAtk** [comment]
@davralin @Protektor-Desura 

Would storing the files in the Lidarr artist folder suffie as an option? That is the direction I'm thinking of going with enabling sub-folder support...

**Comment by Protektor-Desura** [comment]
You mean like: 
/music/Steely Dan/

I would prefer:
/music-videos/Steely Dan/

like that. If you mean use Lidarr artist names, then I'm cool with that. I would just mention that for Lidarr artist I do:
{Artist Name}{ (Artist Disambiguation)}

**Comment by davralin** [comment]
> @davralin @Protektor-Desura
> 
> Would storing the files in the Lidarr artist folder be adequate as an option? That is the direction I'm thinking of going with enabling sub-folder support...

If you output `/downloads-amvd/<artist-folder-name-as-given-in-lidarr>/video.mkv`, I would be very pleased, and it would be a perfect fit for a flat file-strutcture.

**Comment by RandomNinjaAtk** [comment]
@Protektor-Desura @davralin 

All changes should be complete, when you pull the new image with v1.1.1

For ref: https://github.com/RandomNinjaAtk/docker-amvd/commit/a04ee1add9daa851907d1b77f691297e2415f3e6

Please test accordingly...

**Comment by davralin** [comment]
Good to hear, I'll have to postpone the check, but should get to it this weekend at the latest.

And thanks! :-)

**Comment by davralin** [comment]
I was able to start it during the weekend, but haven't had the time to check up on it before now.

It seems to be working, I have folders in the output.

It hasn't downloaded a single video though, and docker logs is spewing out `No such file or directory` on the json-files from the cache.

I.e: `cat: /config/cache/Ludwig.van.Beethoven-1f9df192-a621-4f54-8850-2c5373b7eac9-recording-count.json: No such file or directory`

At least the artist folder is working!

Not sure if I should create a different issue, or if you know about the error without further logs?

**Comment by RandomNinjaAtk** [comment]
Have you made sure your fully updated? You also may want to jump on discord...

**Comment by davralin** [comment]
```
2020-09-08 20:12:59 ############################################ SCRIPT VERSION 1.1.18
2020-09-08 20:12:59 ############################################ DOCKER VERSION 1.0.5
```
Yup.

I'll try looking into it some more, I'm thinking this is on my side somewhere.
