### ISSUE TITLE
Automatically updating scripts

### ISSUE THREAD

**Issue by karbowiak** [RandomNinjaAtk/docker-amvd#24]
Hello there, would it be possible to add a flag to NOT automatically delete the /config/scripts folder on startup?

**Comment by RandomNinjaAtk** [comment]
Made some changes that should accomplish this feature request, give it a try after everything updates

**Comment by RandomNinjaAtk** [comment]
All development is being moved to: https://github.com/RandomNinjaAtk/docker-lidarr-extended
