### ISSUE TITLE
Feature Request: Blacklist / Filter video title terms

### ISSUE THREAD

**Issue by lengland** [RandomNinjaAtk/docker-amvd#27]
I've just set this up and had it run against a small library, awesome tool by the way! I've have noticed that it is pulling down Lyric Videos. 
Example Artist: Taylor Swift

Is there a way to have amvd not download the videos with "Lyric" or "Lyric Video" in the title?

**Comment by RandomNinjaAtk** [comment]
All development is being moved to: https://github.com/RandomNinjaAtk/docker-lidarr-extended
