### ISSUE TITLE
Recent issue with renaming

### ISSUE THREAD

**Issue by kingofdunghill** [RandomNinjaAtk/docker-amvd#28]
Hi,

first: thanks for this great tool.

Unfortunately since a recent update the renaming isnt working here anymore (settings
 stayed the same) . In the tmp folder filename is artist and songname but in downloads-amvd it consists only of songname. After that also chmod fails because there is not the expected full filename.

Thanks for looking over it.

[script_run_1_2022_05_27_12_01_PM.log](https://github.com/RandomNinjaAtk/docker-amvd/files/8786737/script_run_1_2022_05_27_12_01_PM.log)

**Comment by kingofdunghill** [comment]
Hm. Have tried everything, also with combinations of USEFOLDERS and USEVIDEOFOLDERS true/false. No change to get the file renamed with artist - songname.mkv again. Is this change intended?

**Comment by kingofdunghill** [comment]
The problem is that the music video files are no longer recognized correctly in jellyfin as they were before. At that time they were displayed in the artist folder under the music videos category as intended.

**Comment by kingofdunghill** [comment]
I've also WriteNFOs=true activated but only *.jpg is created in the folder.

**Comment by jaycedk** [comment]
Seeing the same, and Emby is on longer matching the video to artist.

**Comment by RandomNinjaAtk** [comment]
All development is being moved to: https://github.com/RandomNinjaAtk/docker-lidarr-extended
