### ISSUE TITLE
Feature Request: save the music video next to the matching track

### ISSUE THREAD

**Issue by ecarlson94** [RandomNinjaAtk/docker-amvd#29]
Is there a way to save the music video next to the matching track with the same name as the music file. The reason I ask is because plex can automatically associate music videos to tracks.

Here is a tip from their [support page](https://support.plex.tv/articles/205568377-adding-local-artist-and-music-videos/) in this topic:
>Tip!: To have the music video associated with the track, it must start with the exact filename of the corresponding music track and must be in the same directory as that track.

**Comment by RandomNinjaAtk** [comment]
All development is being moved to: https://github.com/RandomNinjaAtk/docker-lidarr-extended
