### ISSUE TITLE
Date metadata in MKV files

### ISSUE THREAD

**Issue by monkeyhat** [RandomNinjaAtk/docker-amvd#5]
I tried adding my music videos folder as an "Other Videos" library in Plex, and noticed that it was actually picking up a reasonable amount of metadata from MP4 files created by AMVD, but not much from MKVs.  One thing I was looking for was year information, as Plex seems to categorise and collect the videos according to this (among other things.)  However, Plex always shows MKVs from AMVD dated as "2020"

I was trying to work out why this was, as - In the script - I noticed that the date is being stored in the MKV metadata:  
`-metadata DATE_RELEASE="$year" \`

I loaded one of the files into mkvtoolnix, but couldn't find the date info.  Though I noticed that, in the Header Editor, it's possible to add a "Date" tag.  

![mkvtoolnix](https://user-images.githubusercontent.com/7346670/93535070-2313a500-f93e-11ea-8c25-ea4aadb1e0a0.jpg)

With that set, Plex then DOES pick up the year.  

Is it possible for AMVD to set this, or would that be beyond the scope as it might be a Plex-specific issue?

**Comment by RandomNinjaAtk** [comment]
If you can test if ffmpeg can tag it, then I can add it in

**Comment by monkeyhat** [comment]
Thanks for this!  I had a look through and tried every option I could think of to try and get FFMPEG to do the same as MKVMerge-GUI was doing, but I had no luck.  In fact I couldn't really find a way to view the MKVMerge date stuff anywhere but MKVMerge and Plex - so I think it's probably more a fluke that it worked than anything, and not worth pursuing.  

Is there any way to get AMVD to export videos in MP4 format?  As mentioned, I had some MP4 music videos (which must've been created by an older version of the script, as I believe it only generates MKVs now) - and the Plex "Other videos" local metadata handler seemed to manage quite well with those - properly handling things like the year and the artist.  Though, as this is probably more of an issue with the way Plex handles MKVs, I totally understand if not!

**Comment by RandomNinjaAtk** [comment]
I always debate what format to use, your right that MP4 supports tagging better and most software reads them. MKV tags aren't really used at all from what I can tell from most applications from my personal testing.

The reason to move to MKV was to simplify and standardize, instead of supporting multiple options. Because MP4 has codec (video/audio/subtitle) limitations that MKV does not...

I personally always feel conflicted on what container to use because of these limitations... If mp4 didn't have the same limitations, it would probably be the right choice for that reason...

So I'm not sure if I will enable an option or switch because I want to keep things simple...

**Comment by davralin** [comment]
https://forums.plex.tv/t/lma-agent-mkv-metadata-still-not-parsing/562298

For context, also read this from 2016:
https://forums.plex.tv/t/mkv-metadata/100607/2

It seems, plex doesn't do metadata from mkv...

**Comment by monkeyhat** [comment]
Thanks for the responses, both.  I totally understand the decision to stick with MKV - I use it for everything else as it seems to be a way more capable container (particularly for things like subtitles) - I just thought MP4 might be a work-around in this case.  Plex's response to not reading MKV metadata seems pretty much in-line with company policy - "why do something consistently?"  

One potential solution: I noticed that someone's made a [Plex agent](https://forums.plex.tv/t/nfo-agent/4688/354) that reads metadata from NFO files.  It seems to mainly be geared for movie and TV libraries, and for moving libraries across from XBMC - but Plex allows you to choose an agent for "Other Videos" libraries, so I'm going to give it a try with the NFO files generated by AMVD.  Will let you know how it works out! 

Thanks again!

**Comment by davralin** [comment]
I parse info.json with jq, and then I touch the file based on that, the files access/modification-time is honored.
Something like:
```
UPLOAD_DATE=$(/usr/bin/cat movie.info.json | /usr/bin/jq .upload_date | /usr/bin/sed 's/"//g' | /usr/bin/sed 's/$/0000/g')
/usr/bin/touch -a -m -t $UPLOAD_DATE movie.*
```
info.json is populated with `--write-info-json` passed to youtube-dl

**Comment by RandomNinjaAtk** [comment]
Recent updates change this to using MP4, so this is resolved... @monkeyhat
