### ISSUE TITLE
Fallback to IMVDb lookup when MusicBrainz doesn't have IMVDb link?

### ISSUE THREAD

**Issue by flexage** [RandomNinjaAtk/docker-amvd#6]
Hey, first off, great project!

It seems we're relying on MusicBrainz actually having the IMVDb link added for an artist.

In my usage of AMVD so far, it seems I have a lot of artists who exist on IMVDb but don't have the link added to their MusicBrains info.

Would it be possible to add a feature, that in the event of MusicBrainz not having the link added to an artist, that we could do an artist lookup on the IMVDb api?

I am aware that IMVDb does rate limiting, so each user would ideally need their own key so as not to max out a shared request pool. Maybe providing your own API credentials could be a configurable option?

I also understand that whenever we are doing a string query against an API, that there is always margin for error when matching against the desired result. However for those of us who might prefer a fully automated experience, it would be nice to be able to enable this fallback to IMVDb lookup in the config, so as not to damage the Out Of Box experience for general users who may not need this feature.

I know that I would much prefer that a IMVDb lookup was performed, rather than having to look up the artist on MusicBrainz, then source and add the link to the relevant IMVDb page there, as I'm having to do currently.

I wouldn't mind if it was just missing one or 2 artists, but it misses a lot of the artists in my collection.

Thanks again for your great work on this project :+1:

Edit: typos

**Comment by RandomNinjaAtk** [comment]
I would prefer not too because there is a chance you won't get the right data. It's preferable to update Musicbrainz with the links to resolve that kind of problem...

Also from the last time I looked at it, there api is very lacking so I'm not sure if it would be possible.

If you want to write a PR for such feature and it works fine, I'm not opposed to it...

**Comment by flexage** [comment]
Thanks for the response. I would give it a go, but while my terminal/shell skills are ok, I don't think they're up to the level needed to pull this off.

I was aware that adding an artist lookup on IMVDb may introduce uncertainty when matching artists, which is why my initial thought was to make this fallback something which was disabled by default, but could be enabled in the config by willing ~victims~ participants

All cool though, was just a thought, I'm happy to update MusicBrainz with the IMVDb link.

As an aside though, when I do update MusicBrainz with the IMVDb link, I then have to either wait for AMVD to mark the cache for that artist as expired, or go and manually delete the JSON cache files for that artist. Can you suggest a better workflow for this scenario that doesn't require as much manual interaction?

**Comment by RandomNinjaAtk** [comment]
It sort of expires the cache every 7 days. So if you wait long enough, it should do its thing...

**Comment by KINGLIFER** [comment]
A bit late to the game but I would honestly prefer a simple youtube search to add to it. I find if I search vevo + official with artist name you get all the tracks. If you want specific you can also put track name. 

I doubt it will be added but that would be awesome. I use the videos to mix music actually. (video dj)
